apiVersion: v1
kind: Service
metadata:
  name: datetime-service
spec:
  selector:
    app: datetime
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # Change to NodePort if not on a cloud provider

